name: 京东京喜工厂

on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *"
  watch:
    types: [started]
  repository_dispatch:
    types: jd_dreamFactory

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout github_sazs34_MyActions
        uses: actions/checkout@v2
        with:
          repository: 18u/github_sazs34_MyActions
          ref: master
          path: scripts
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run: |
          cd scripts
          npm install
      - name: "运行【京东京喜工厂】"
        run: |
          cd scripts
          node onlyOneExecute.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          SYNCURL: https://github.com/18u/github_lxk0301_jd_scripts/raw/master/jd_dreamFactory.js
