name: jd_digital_floor

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "15 7,16 * * *"
  watch:
    types: [started]
  repository_dispatch:
    types: jd_digital_floor

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: fq3/gitee_lxk0301_jd_scripts
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: npm install
      - name: prepare job
        run: |
          rm -rf jdCookie.js
          wget -q -O jdCookie.js https://github.com/fq3/gitee_lxk0301_jd_scripts/raw/cd33b4f47e77387bace6505167d50912fb4abf33/jdCookie.js
      - name: "Run Job"
        run: node activity/jd_digital_floor.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
