name: repo-sync
on:
  schedule:
    - cron: '15 2,14 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: repo-sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id && github.repository != 'uuz/actions'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

#       - name: sync 
#         uses: repo-sync/github-sync@v2
#         if: env.PAT
#         with:
#           source_repo: "https://github.com/uuz/actions.git"
#           source_branch: "main"
#           destination_branch: "main"
#           github_token: ${{ secrets.PAT }}

      - name: Sync repo to branch
        uses: repo-sync/github-sync@v2
        with:
          source_repo: https://github.com/uuz/actions.git
          source_branch: main
          destination_branch: upstream
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: upstream
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
